### ISSUE TITLE
it is too slow in running sgm.

### ISSUE THREAD

**Issue by If-only1** [2b-t/stereo-matching#1]
i can't get the resulet of sgm, it is too slow?

**Comment by 2b-t** [comment]
Hey @If-only1 
Semi-global matching (SGM) is quite a bit slower than Winner Takes it All (WTA) but you should be able to run less in a matter of several seconds if I remember correctly (I can test how long it takes on my workstation in the evening.) even on a low-power notebook **as long as you use [numba](https://numba.pydata.org/)**. If you would uncomment numba (jit decorators) you might end up with a code that might take very long as it then uses loops in native Python (which is very slow). Another reason that might make it slow is running it inside a virtual machine which is underpowered.

What test image are you using (resolution) and what is your set-up (CPU, RAM, OS, VM?, Python version)? Did you leave the disparity and radius settings on default?

**Comment by 2b-t** [comment]
Closed due to inactivity.

**Comment by If-only1** [comment]
thansk for you answer.
I have solved this problem by repalace"@jit(nopython = True, parallel = True, cache = True)"  as "@jit"
